on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Define env name'
          required: true
          default: 'prod'
        branch:
          description: 'Define branch name'
          required: true
          default: 'master'

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.environment }}